spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/noni_lab
    username: root
    password: password
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
#    drop-first: true